#!/bin/bash
### BEGIN INIT INFO
# Provides:          vnc
# Required-Start:    $network $local_fs
# Required-Stop:
# Should-Start:      $syslog
# Should-Stop:       $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: tightvnc for pi
# Description:       whatever
### END INIT INFO


# Carry out specific functions when asked to by the system
case "$1" in
start)
    su pi -c '/usr/bin/vncserver -geometry 800x600 :1'
    echo "Starting VNC server "
    ;;
stop)
    pkill Xtightvnc
    echo "VNC Server has been stopped (didn't double check though)"
    ;;
status)
    ps -C Xtightvnc
    ;;
*)
    echo "Usage: /etc/init.d/blah {start|stop}"
    exit 1
    ;;
esac

exit 0
